# Settings

set allow-duplicate-recipes := true
set allow-duplicate-variables := true
set dotenv-filename := ".env"
set dotenv-load := true
set dotenv-path := "."
set dotenv-required := false
set export := true
set fallback := true
set ignore-comments := false
set positional-arguments := true
set shell := ["bash", "-uc"]
set tempdir := "/tmp"
set windows-powershell := false
set windows-shell := "cmd"
set unstable := true

# Boolean not required 

set allow-duplicate-recipes
