version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'npm dependencies'
      - 'dependabot'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'github-actions'
      - 'dependabot'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'docker'
      - 'dependabot'
