version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'yearly'
    labels:
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'yearly'
    labels:
      - 'dependencies'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'yearly'
    labels:
      - 'dependencies'
