# Disabled to avoid noise due to low risk and update frequency of this repo
# version: 2
# updates:
#   - package-ecosystem: 'npm'
#     directory: '/'
#     schedule:
#       interval: 'monthly'
#     labels:
#       - 'dependencies'
#   - package-ecosystem: 'github-actions'
#     directory: '/'
#     schedule:
#       interval: 'monthly'
#     labels:
#       - 'dependencies'
#   - package-ecosystem: 'docker'
#     directory: '/'
#     schedule:
#       interval: 'monthly'
#     labels:
#       - 'dependencies'
