version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sleep infinity
    environment:
      - NODE_ENV=developement
    volumes:
      - ./:/code
      - node_modules:/code/node_modules

volumes:
  node_modules:
