services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sleep infinity
    environment:
      - NODE_ENV=developement
    volumes:
      - ./:/code
      - /code/node_modules
